// <auto-generated />
using System;
using Gotcha.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gotcha.Core.Migrations
{
    [DbContext(typeof(GotchaDbContext))]
    partial class GotchaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Gotcha.Core.Entities.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.PrimitiveCollection<string>("AdminIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("HasStarted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFinished")
                        .HasColumnType("bit");

                    b.Property<int>("MaxPlayers")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("RulesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("WinnerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RulesId")
                        .IsUnique();

                    b.ToTable("Games");
                });

            modelBuilder.Entity("Gotcha.Core.Entities.Kill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsValid")
                        .HasColumnType("bit");

                    b.Property<string>("KillMessage")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("KillerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Moment")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("TimeSinceAssignedTarget")
                        .HasColumnType("bigint");

                    b.Property<Guid>("VictimId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Weapon")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("KillerId");

                    b.HasIndex("VictimId");

                    b.ToTable("Kills");
                });

            modelBuilder.Entity("Gotcha.Core.Entities.Logging.Attacker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("InvalidInput")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("MacAddress")
                        .HasMaxLength(17)
                        .HasColumnType("nvarchar(17)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Referer")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SessionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Attackers");
                });

            modelBuilder.Entity("Gotcha.Core.Entities.Logging.Log", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AttackerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ExtraInfo")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("LogGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("LogSubType")
                        .HasColumnType("int");

                    b.Property<int>("LogType")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AttackerId");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("Gotcha.Core.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsAlive")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ProfileImageSource")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Username")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Gotcha.Core.Entities.Rules", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("ChaosTimer")
                        .HasColumnType("bigint");

                    b.Property<bool>("CustomKillMethods")
                        .HasColumnType("bit");

                    b.Property<string>("CustomRules")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("EnforcePlayerImages")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAssassin")
                        .HasColumnType("bit");

                    b.Property<bool>("IsChaos")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTimed")
                        .HasColumnType("bit");

                    b.Property<long>("KillConfirmationTimer")
                        .HasColumnType("bigint");

                    b.PrimitiveCollection<string>("KillMethods")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ShowPlayerImages")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowRealNames")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowUsernames")
                        .HasColumnType("bit");

                    b.Property<long>("TargetTimeOut")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Rules");
                });

            modelBuilder.Entity("Gotcha.Core.Entities.TargetAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AssignmentFinished")
                        .HasColumnType("datetime2");

                    b.Property<int>("AssignmentStatus")
                        .HasColumnType("int");

                    b.Property<Guid>("HunterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("KillId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TargetAssigned")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Weapon")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("HunterId");

                    b.HasIndex("KillId")
                        .IsUnique()
                        .HasFilter("[KillId] IS NOT NULL");

                    b.HasIndex("TargetId");

                    b.ToTable("TargetAssignments");
                });

            modelBuilder.Entity("Gotcha.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AccountCreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProfileImageSource")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Gotcha.Core.Entities.VipSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AssassinModeUnlocked")
                        .HasColumnType("bit");

                    b.Property<bool>("ChaosModeUnlocked")
                        .HasColumnType("bit");

                    b.Property<bool>("CustomKillMethodsUnlocked")
                        .HasColumnType("bit");

                    b.Property<int>("MaxLobbySize")
                        .HasColumnType("int");

                    b.Property<bool>("TimedKillsUnlocked")
                        .HasColumnType("bit");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("UserPlan")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("VipSettings");
                });

            modelBuilder.Entity("Gotcha.Core.Entities.Game", b =>
                {
                    b.HasOne("Gotcha.Core.Entities.Rules", "Rules")
                        .WithOne()
                        .HasForeignKey("Gotcha.Core.Entities.Game", "RulesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rules");
                });

            modelBuilder.Entity("Gotcha.Core.Entities.Kill", b =>
                {
                    b.HasOne("Gotcha.Core.Entities.Game", "Game")
                        .WithMany("Kills")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gotcha.Core.Entities.Player", "Killer")
                        .WithMany()
                        .HasForeignKey("KillerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Gotcha.Core.Entities.Player", "Victim")
                        .WithMany()
                        .HasForeignKey("VictimId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Killer");

                    b.Navigation("Victim");
                });

            modelBuilder.Entity("Gotcha.Core.Entities.Logging.Log", b =>
                {
                    b.HasOne("Gotcha.Core.Entities.Logging.Attacker", "Attacker")
                        .WithMany()
                        .HasForeignKey("AttackerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Attacker");
                });

            modelBuilder.Entity("Gotcha.Core.Entities.Player", b =>
                {
                    b.HasOne("Gotcha.Core.Entities.Game", "Game")
                        .WithMany("Players")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gotcha.Core.Entities.User", "User")
                        .WithMany("PlayerAccounts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Gotcha.Core.Entities.TargetAssignment", b =>
                {
                    b.HasOne("Gotcha.Core.Entities.Player", "Hunter")
                        .WithMany("TargetAssignments")
                        .HasForeignKey("HunterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Gotcha.Core.Entities.Kill", "Kill")
                        .WithOne()
                        .HasForeignKey("Gotcha.Core.Entities.TargetAssignment", "KillId");

                    b.HasOne("Gotcha.Core.Entities.Player", "Target")
                        .WithMany()
                        .HasForeignKey("TargetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Hunter");

                    b.Navigation("Kill");

                    b.Navigation("Target");
                });

            modelBuilder.Entity("Gotcha.Core.Entities.VipSettings", b =>
                {
                    b.HasOne("Gotcha.Core.Entities.User", null)
                        .WithOne("VipSettings")
                        .HasForeignKey("Gotcha.Core.Entities.VipSettings", "UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Gotcha.Core.Entities.Game", b =>
                {
                    b.Navigation("Kills");

                    b.Navigation("Players");
                });

            modelBuilder.Entity("Gotcha.Core.Entities.Player", b =>
                {
                    b.Navigation("TargetAssignments");
                });

            modelBuilder.Entity("Gotcha.Core.Entities.User", b =>
                {
                    b.Navigation("PlayerAccounts");

                    b.Navigation("VipSettings")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
